name: Build and release

on:
  push:
    tags: 'v*'

jobs:

  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"

      - name: Set Environment
        run: powershell (new-object Net.WebClient).DownloadFile('https://github.com/SkyTeamWater/res/releases/download/v1.0.0e/e.zip','D:\e.zip') && powershell (new-object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/SkyTeamWater/res/v1.0.0e/ecl.exe','D:\ecl.exe') && expand -F:* D:\e.zip D:\ && D:\ecl.exe set epath "D:\e\e.exe" 
      
      - name: Build
        run: make.bat && D:\ecl make "e\MinecraftSpeedProxy.e" "MinecraftSpeedProxy.exe"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            MinecraftSpeedProxy.exe
            core.dll
